DROP TABLE IF EXISTS TWEETS;

CREATE TABLE TWEETS (
  user_id BIGINT PRIMARY KEY,
  text VARCHAR(1000) NOT NULL,
  user_name VARCHAR(100) NOT NULL,
  validated BOOLEAN NOT NULL,
  locale VARCHAR(20) NOT NULL,
);